### ISSUE TITLE
Add chromecast support

### ISSUE THREAD

**Issue by jprberlin** [openHPI/android-app#1]
Simple Szenario: Watch picture in picture Video on Chromecast Device
Complex Szenario: Watch dual stream videos one on the video, the other on the device

**Comment by rhlff** [comment]
Open smaller tasks:
- [ ] Styling of MediaRouter Dialog (some buttons white on white)
- [ ] Correct bottom placement of MiniController and try to place one controller on top of ViewPager
- [ ] Parent Activity Bug for VideoCastControllerActivity
- [ ] "Introducing Cast to new users“ overlay doesn't show up
- [ ] Styled Media Receiver applications for different build variants

Open bigger task:
- [ ] Rafactor VideoController and improve video experience with Cast

**Comment by rhlff** [comment]
Comment on task Styling of MediaRouter Dialog (some buttons white on white):
This is a bug of `android.support.v7.app.MediaRouteControllerDialog` from the MediaRouter Support Library, which is already reported:
https://code.google.com/p/android/issues/detail?id=198714

**Comment by jprberlin** [comment]
:+1:
