### ISSUE TITLE
Download folder should be exluded from auto backups

### ISSUE THREAD

**Issue by jprberlin** [openHPI/android-app#10]

**Comment by rhlff** [comment]
What backup tool are you using?

**Comment by jprberlin** [comment]
I was referring this: http://developer.android.com/training/backup/autosyncapi.html We should make sure that no unimportant data is backed up.

**Comment by rhlff** [comment]
I think we are fine with the default configuration:

**Automatically excluded data files**

Most apps do not need to, and in fact should not, back up all data. For example, the system should not back up temporary files and caches. For this reason, the automatic backup service excludes certain data files by default:

* Files in the directories to which the `getCacheDir()` and `getCodeCacheDir()` methods refer.
* Files located on external storage, unless they reside in the directory to which the `getExternalFilesDir()` method refers.
* Files located in the directory to which the `getNoBackupFilesDir()` method refers.

Our downloaded files are saved in `Environment.getExternalStorageDirectory()`, which is exluded from auto backups. Unless you're not doing a manual back up of your external storage.

**Comment by jprberlin** [comment]
OK, great. Thanks for checking.
